FROM docker.funf/build/oraclelinux9 as oraclelinux

RUN yum update -y && yum install -y \
    rpmdevtools rpm-build rpm-sign \
    && yum clean all \
    && rm -rf /var/cache/yum/*

ENV A Bcaaaaaaaa
USER works
WORKDIR /home/works