FROM docker.funf/build/oraclelinux8 as oraclelinux

RUN yum update -y && yum install -y \
    rpmdevtools rpm-build rpm-sign \
    && yum clean all \
    && rm -rf /var/cache/yum/*

USER works
WORKDIR /home/works