FROM docker.funf/oraclelinux:9 as files

ADD files /files
RUN chmod 644 /files/etc/pki/rpm-gpg/RPM-GPG-KEY-oracle

FROM docker.funf/oraclelinux:9 as oraclelinux

COPY --from=files /files /

RUN yum update -y && yum install -y \
    ca-certificates \
    git wget curl \
    zip unzip \
    && yum clean all \
    && rm -rf /var/cache/yum/* \
    && update-ca-trust

SHELL [ "/bin/bash", "-lc" ]