FROM docker.funf/oraclelinux:9 as files

ADD files /files
RUN chmod 644 /files/etc/pki/rpm-gpg/RPM-GPG-KEY-oracle

FROM docker.funf/oraclelinux:9 as oraclelinux

COPY --from=files /files /

ENV TZ Asia/Singapore
ENV LANG C.UTF-8

RUN yum update -y && yum install -y \
    mobilesolutionworks-ca \
    git wget curl \
    zip unzip \
    && yum clean all \
    && rm -rf /var/cache/yum/*

SHELL [ "/bin/bash", "-lc" ]