name: work

on:
  push:
    branches: [ main, develop ]

jobs:
  ubuntu-lunar:
    name: ubuntu-lunar
    runs-on: self-hosted
    container:
      image: docker.funf/docker:dind
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: mobilesolutionworks/gha-publish-containerfile-action@main
        with:
          path: ubuntu-lunar
          tag: registry.funf/build/ubuntu-lunar

  oraclelinux9:
    name: oraclelinux9
    runs-on: self-hosted
    container:
      image: docker.funf/docker:dind
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: mobilesolutionworks/gha-publish-containerfile-action@main
        with:
          path: oraclelinux9
          tag: registry.funf/build/oraclelinux9

  oraclelinux9-pkg:
    name: oraclelinux9-pkg
    needs: [ oraclelinux9 ]
    runs-on: self-hosted
    container:
      image: docker.funf/docker:dind
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: mobilesolutionworks/gha-publish-containerfile-action@main
        with:
          path: oraclelinux9-pkg
          tag: registry.funf/build/oraclelinux9-pkg
