name: work

# Triggers for when the workflow will run
on:
  push:
    branches: [ main, develop ]

jobs:
  oraclelinux9:
    name: oraclelinux9
    if: ${{ contains(github.event.push.paths, 'oraclelinux9/') }}
    outputs:
      oraclelinux9: ${{ steps.decide.outputs.oraclelinux9 }}
    runs-on: self-hosted
    container:
      image: docker.funf/docker:dind
      options: --privileged
    steps:
      # The "actions/checkout" action helps pull your code from GitHub into the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd oraclelinux9
          echo "jenkins" | docker login registry.funf -u jenkins --password-stdin 
          docker build --compress --pull --rm -t registry.funf/build/oraclelinux . --file Containerfile
          docker push registry.funf/build/oraclelinux
      - name: Decide if Child1 should run
        id: decide
        run: echo "::set-output name=success::true"

  oraclelinux9-pkgrpm:
    name: oraclelinux9-pkgrpm
    needs: [ oraclelinux9 ]
    if: ${{ needs.oraclelinux9.outputs.success == 'true' || contains(github.event.push.paths, 'oraclelinux9-pkgrpm/') }}
    runs-on: self-hosted
    container:
      image: docker.funf/docker:dind
      options: --privileged
    steps:
      # The "actions/checkout" action helps pull your code from GitHub into the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd oraclelinux9
          echo "jenkins" | docker login registry.funf -u jenkins --password-stdin 
          docker build --compress --pull --rm -t registry.funf/build/oraclelinux . --file Containerfile
          docker push registry.funf/build/oraclelinux
