name: work

# Triggers for when the workflow will run
on:
  push:
    branches: [ main, develop ]

jobs:
  oraclelinux9:
    name: oraclelinux9
    runs-on: self-hosted
    container:
      image: docker.funf/docker:dind
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd oraclelinux9
          echo "jenkins" | docker login registry.funf -u jenkins --password-stdin 
          docker build --compress --pull --rm -t registry.funf/build/oraclelinux . --file Containerfile
          docker push registry.funf/build/oraclelinux

  oraclelinux9-pkgrpm:
    name: oraclelinux9-pkgrpm
    needs: [ oraclelinux9 ]
    runs-on: self-hosted
    container:
      image: docker.funf/docker:dind
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd oraclelinux9-pkgrpm
          echo "jenkins" | docker login registry.funf -u jenkins --password-stdin 
          docker build --compress --pull --rm -t registry.funf/build/oraclelinux9-pkgrpm . --file Containerfile
          docker push registry.funf/build/oraclelinux9-pkgrpm
