name: works

on:
  push:
    branches: [ main, develop ]

jobs:
  works:
    name: works
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Publish
        run: gradle build-all